site_name: DPGCM Resources
theme:
  name: material
  features:
    - content.action.edit
repo_url: https://github.com/bonniewolfe/dpgcm-resources
repo_name: bonniewolfe/dpgcm-resources
edit_uri: edit/main/docs/
